# Ideally cluster-1 will have it's own flux install.  
# This is to mock the flux install that will be applied directly in cluster-1
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: add-clusters-1-kustomization
  namespace: flux-system
spec:
  interval: 1m0s
  path: clusters/cluster-1
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
status: {}
